third_party_options:
  application_industries:
    KYMP: KYMP
    SOTE: SOTE
    KANSLIA: KANSLIA
    PEL: PEL
    KUVA: KUVA
    KASKO: KASKO
  applicant_types:
    registered_community: 'Rekisteröity yhdistys'
    unregistered_community: 'Rekisteröimätön yhdistys'
    private_person: Yksityishenkilö
  application_types:
    29:
      id: ECONOMICGRANTAPPLICATION
      code: YLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\YleisavustusHakemusDefinition
        definitionId: grants_metadata_yleisavustushakemus
      labels:
        fi: 'Kaupunginhallituksen yleisavustushakemus'
        en: 'EN Kaupunginhallituksen yleisavustushakemus'
        sv: 'SV Kaupunginhallituksen yleisavustushakemus'
    48:
      id: KUVAPROJ
      code: KUVAPROJ
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaProjektiDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Taide ja kulttuuri: projektiavustus'
        en: 'EN Taide ja kulttuuri: projektiavustus'
        sv: 'SV Taide ja kulttuuri: projektiavustus'
    49:
      id: KUVAKEHA
      code: KUVAKEHA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaKehaDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Taide ja kulttuuri: kehittämisavustus'
        en: 'EN Taide ja kulttuuri: kehittämisavustus'
        sv: 'SV Taide ja kulttuuri: kehittämisavustus'
    51:
      id: KASKOYLEIS
      code: KASKOYLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KaskoYleisavustusDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Kasvatus ja koulutus: yleisavustushakemus'
        en: 'EN Kasvatus ja koulutus: yleisavustushakemus'
        sv: 'SV Kasvatus ja koulutus: yleisavustushakemus'
    47:
      id: KUVATOIM
      code: KUVATOIM
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaToimintaDefinition
        definitionId: grants_metadata_kuvatoiminta
      labels:
        fi: 'Taide ja kulttuuri: toiminta-avustus'
        en: 'EN Taide ja kulttuuri: toiminta-avustus'
        sv: 'SV Taide ja kulttuuri: toiminta-avustus'
  application_statuses:
    DRAFT: DRAFT
    SENT: SENT
    SUBMITTED: SUBMITTED
    RECEIVED: RECEIVED
    PENDING: PENDING
    PROCESSING: PROCESSING
    READY: READY
    DONE: DONE
    REJECTED: REJECTED
    DELETED: DELETED
    CANCELED: CANCELED
    CANCELLED: CANCELLED
    CLOSED: CLOSED
  subvention_types:
    1: Toiminta-avustus
    2: Palkkausavustus
    4: Projektiavustus
    5: Vuokra-avustus
    6: Yleisavustus
    7: 'Työttömien koulutusavustus'
    8: 'Korot ja lyhennykset'
    9: Muu
    11: Kuljetusavustus
    12: Leiriavustus
    13: Maksuvapauskompensaatio
    14: Lisäavustus
    15: Suunnistuskartta-avustus
    17: 'Toiminnan kehittämisavustus'
    29: 'Kehittämisavustukset / Helsingin malli'
    31: Starttiavustus
    32: Tilankäyttöavustus
    34: 'Taiteen perusopetus'
    35: Varhaiskasvatus
    36: 'Vapaa sivistystyö'
    37: Tapahtuma-avustus
    38: Pienavustus
    39: Kotouttamisavustus
    40: Harrastushaku
    41: Laitosavustus
    42: 'Muiden liikuntaa edistävien yhteisöjen avustus'
    43: Kohdeavustus
langcode: fi
